version: '3.8'

services:
  ollama:
    image: ollama/ollama:latest
    container_name: ollama
    entrypoint: ["sh", "-c"]
    command: >
      "
      ollama serve &
      sleep 5 &&
      ollama pull llama3 &&
      tail -f /dev/null
      "
    ports:
      - "11434:11434"
    volumes:
      - ollama_models:/root/.ollama
    networks:
      - mcp-network

  db:
    image: postgres:15
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: cars_db
    ports:
      - "7654:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U user -d cars_db"]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - mcp-network

  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: mcp-api-app
    depends_on:
      db:
        condition: service_healthy
    environment:
      - DATABASE_URL=postgresql://user:password@db:5432/cars_db
      - OLLAMA_API_URL=http://ollama:11434/api/generate
      - OLLAMA_MODEL_NAME=llama3
    volumes:
      - type: bind
        source: .
        target: /app
        consistency: cached
    working_dir: /app
    ports:
      - "8000:8000"
    command: uvicorn main:app --host 0.0.0.0 --port 8000
    networks:
      - mcp-network

  terminal:
    build:
      context: .
    container_name: mcp-terminal
    command: python terminal_runner.py
    depends_on:
      db:
        condition: service_healthy
    stdin_open: true
    tty: true
    networks:
      - mcp-network

volumes:
  postgres_data:
  ollama_models:

networks:
  mcp-network:
    driver: bridge